---
title: "hypotheses"
author: "Santi Allende"
date: "4/7/2020"
output: html_document
---

## **Hypotheses**

### **Primary Hypotheses**

*Hypothesis 1a.* Greater cIIV will be associated with greater trait negative affect measured by the Positive and Negative Affect Schedule (PANAS).

*Hypothesis 1b.* Greater cIIV will be associated with lower trait positive affect measured by the PANAS.

*Hypothesis 2a.* Experiencing greater cIIV during the current day relative to cIIV found in other days will be associated with higher negative affect during the current day.

*Hypothesis 2b.* Experiencing greater cIIV during the current day relative to cIIV found in other days will be associated with lower positive affect during the current day.

### **Exploratory Hypotheses**

*Hypothesis 3.* Assess whether cIIV is associated with DCS and AUC.

*Hypothesis 4.* Assess whether latent profile analysis-derived classes of participants based on the CAR, DCS, AUC and cIIV are associated with trait positive and negative affect.
