---
title: "Dissertation"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Abstract

The hypothalamic-pituitary adrenal (HPA) axis is intricately associated with psychological and physical health. Psychological outcomes linked to faulty HPA-axis function include chronic fatigue syndrome, burnout syndrome, sleep disorders, suicide risk, depression, generalized anxiety disorder, posttraumatic stress disorder, fibromyalgia, schizophrenia, bipolar disorders and obsessive-compulsive disorder. Physical outcomes associated with faulty HPA-axis function include tumor progression, cancer survival, congestive heart failure, hypertension, obesity, hyperglycemia, insulin resistance and hyperlipidemia. Hypothalamic-pituitary adrenal (HPA) axis function is commonly measured via cortisol, a glucocorticoid steroid hormone, which is critical to the function of musculoskeletal, cardiovascular, respiratory, endocrine and nervous systems. 

In field research, cortisol is assayed from saliva, which is reliably correlated with free, unbound plasma cortisol. Endogenous cortisol exhibits two distinct rhythms: (1) a circadian ryhthm, which peaks 30-minutes post-wake and reaches a nadir at night and (2) an ultradian rhythm, which peaks approximately once per hour. Three commonly derived measures of diurnal salivary cortisol include: (1) the cortisol awakening response, (2) diurnal salivary cortisol slope and (3) area under the curve. However, a seldom examined measure of salivary cortisol that may provide unique information is cortisol intraindividual secretory variability (cIIV).

Cortisol intraindividual secretory variability has only been examined in the context of depressive and bipolar disorders. Studies have yet to examine cIIV in nonclinical affect presentations. Thus, the primary aim of the present study was to examine whether cIIV is associated with global and daily measures of positive and negative affect in a nonclinical sample. A secondary exploratory aim of the present study was to examine whether person-level profiles of salivary cortisol measures, including the CAR, AUC, DCS and cIIV, are associated with positive and negative affect.


